Description: >
    
    Mohamed BOUSETTA MAHJOUB / Udagram Project : Deploy a high-availability web app using CloudFormation
    This template deploys an Amazon EC2 instance which acts as the Bastion Host. 
    This example creates an EC2 security group for the instance to give you SSH access

Parameters:

    EnvironmentName:
        Description: An environment name that should match the name used to create the network
        Type: String
    
    KeyName: 
        Description: "Name of an existing EC2 KeyPair to enable SSH access to the instance"
        Type: "AWS::EC2::KeyPair::KeyName"

Resources:

    BastionInstance: 
        Type: "AWS::EC2::Instance"
        Properties: 
            InstanceType: t2.micro
            SecurityGroupIds: 
            - !Ref BastionSecurityGroup
            KeyName: !Ref KeyName
            ImageId: ami-003634241a8fcdec0
            SubnetId: 
                Fn::ImportValue: 
                    !Sub "${EnvironmentName}-PUB1-SN"
     
    BastionSecurityGroup: 
        Type: "AWS::EC2::SecurityGroup"
        Properties: 
            GroupDescription: "Enable SSH access via port 22"
            VpcId: 
                Fn::ImportValue: 
                    !Sub "${EnvironmentName}-VPCID"  
            SecurityGroupIngress: 
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp:  "0.0.0.0/0"
      
Outputs: 

    InstanceId: 
        Description: "InstanceId of the newly created EC2 instance"
        Value: !Ref BastionInstance
        Export:
          Name: !Sub ${EnvironmentName}-BastionInstance
 
 
    PublicIP: 
        Description: "Public IP address of the newly created EC2 instance"
        Value: 
            "Fn::GetAtt": 
                - BastionInstance
                - PublicIp
        Export:
          Name: !Sub ${EnvironmentName}-Bastion-PublicIp
 